version: '3.3'

services:
    db:
        image: bitnami/postgresql:11
        ports:  
            - 5435:5432  
        volumes:  
            - postgresql_data:/bitnami/postgresql  
            - ./scripts/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql  
        env_file:  
            - docker.env  
        restart: always  
        networks:  
            - nesjs-network
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        
volumes:
    postgresql_data:
        driver: local


networks:
    nesjs-network: